### PR TITLE
Fix GCE-latest testing

### LINKED ISSUE #119: gce-latest job is failing
Started failing on 6-22. May be related to v1beta1 DaemonSet being removed.

https://k8s-testgrid.appspot.com/sig-storage-local-static-provisioner#master-gce-lastest

/kind failing-test

### PR DESCRIPTION
**Pull request by cofyc**
fixes #119 
why https://github.com/kubernetes/kubernetes/pull/70672

### CODE REVIEW

File: test/e2e/e2e_test.go [hunk 1]
```diff
@@ -29,8 +29,8 @@ import (
 	. "github.com/onsi/ginkgo"
 	. "github.com/onsi/gomega"
 	yaml "gopkg.in/yaml.v2"
-	"k8s.io/api/core/v1"
-	extensionsv1beta1 "k8s.io/api/extensions/v1beta1"
+	appsv1 "k8s.io/api/apps/v1"
+	v1 "k8s.io/api/core/v1"
 	rbacv1beta1 "k8s.io/api/rbac/v1beta1"
```
Comment (msau42) [inline test/e2e/e2e_test.go]: rbac also has a v1 too

Comment (msau42) [reply test/e2e/e2e_test.go]: This can be addressed in a separate pr.
